import {
  promises as fs,
  watch as watchFs,
  watchFile as watchFileFs,
  unwatchFile as unwatchFileFs
} from 'fs'
import { basename, join } from 'path'
import type {
  AlertMeta,
  Category,
  DrawingDoc,
  NibIndex,
  NoteDoc,
  NoteFlag,
  NoteMeta,
  Scope,
  Stroke,
  StrokeTool,
  SubCategory
} from '@shared/types'
import { DEFAULT_TAGS, normalizeTagIds, normalizeTags } from '@shared/tags'
import { DEFAULT_TEMPLATES, normalizeTemplates } from '@shared/templates'
import { ASSETS_DIR, DRAWINGS_DIR, INDEX_FILE, NOTES_DIR } from '@shared/paths'

/**
 * The atomic write comes from `keel/storage`, shared with Jot and Helm.
 *
 * Nib's own copy was Jot's copy, which retried the rename but cleaned up its temp
 * file with a single silent unlink. That loses a race on Windows: the sync client
 * can grab a lock on the temp the instant it appears, and the file is then left
 * behind. Helm found that out the expensive way - 1462 orphaned `.tmp` files in
 * one directory - and the shared version retries the cleanup over the same
 * backoff as the rename.
 *
 * Imported and re-exported: it was exported from here before, and this is still
 * where the rest of the main process looks for it.
 */
import { writeFileAtomic } from 'keel/storage'

export { writeFileAtomic }

/*
 * The shape of the file on disk.
 *
 * 1 - the original.
 * 2 - notes carry `links`, the ids of the notes they link to. Anything written by
 *     version 1 has none, and they cannot be guessed from the index alone - the
 *     links are in the note bodies - so loading an older index triggers a one-off
 *     scan. See `backfillLinks`.
 */
const INDEX_VERSION = 2

const EMPTY_INDEX: NibIndex = {
  version: INDEX_VERSION,
  categories: [],
  tags: DEFAULT_TAGS,
  templates: DEFAULT_TEMPLATES
}

/**
 * Ids are generated by us, but they arrive here from the renderer and end up in
 * a path, so anything that could escape the data folder is rejected outright.
 */
function safeId(id: string): string {
  if (!/^[A-Za-z0-9_-]+$/.test(id)) {
    throw new Error(`Refusing to touch a file for an unsafe id: ${id}`)
  }
  return id
}

function str(value: unknown, fallback = ''): string {
  return typeof value === 'string' ? value : fallback
}

function num(value: unknown, fallback: number): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback
}

function normalizeScope(value: unknown): Scope {
  return value === 'W' || value === 'P' ? value : ''
}

// Capped on both axes: the index is read on every start and rendered into a
// strip, so one pathological note must not be able to bloat it.
const MAX_ALERTS_PER_NOTE = 24
const MAX_ALERT_TEXT = 160

function normalizeAlerts(raw: unknown): AlertMeta[] {
  if (!Array.isArray(raw)) {
    return []
  }
  return raw
    .filter((entry) => entry !== null && typeof entry === 'object')
    .map((entry) => ({
      id: str((entry as { id?: unknown }).id),
      text: str((entry as { text?: unknown }).text).slice(0, MAX_ALERT_TEXT),
      done: (entry as { done?: unknown }).done === true
    }))
    .filter((alert) => alert.id.length > 0)
    .slice(0, MAX_ALERTS_PER_NOTE)
}

/**
 * A note's flag, accepting the boolean this field used to be.
 *
 * Notes written before the flag had three states carry `flagged: true`, and there
 * is no migration step anywhere in Nib - the normalisers are the migration.
 */
function normalizeFlag(raw: any): NoteFlag {
  if (raw?.flag === 'open' || raw?.flag === 'done') {
    return raw.flag
  }
  return raw?.flagged === true ? 'open' : ''
}

function normalizeSub(raw: any): SubCategory {
  return { id: String(raw?.id ?? ''), name: str(raw?.name) }
}

/**
 * `categoryId` and `subId` are normalised against the note's actual position in
 * the index rather than trusted: the index is the authority on where a note
 * lives, so a stale field copied in by an external writer must not win.
 */
function normalizeNoteMeta(raw: any, categoryId: string, subIds: Set<string>): NoteMeta {
  const created = num(raw?.created, Date.now())
  const subId = str(raw?.subId)
  return {
    id: String(raw?.id ?? ''),
    categoryId,
    subId: subId.length > 0 && subIds.has(subId) ? subId : null,
    title: str(raw?.title),
    preview: str(raw?.preview),
    created,
    edited: num(raw?.edited, created),
    pinned: raw?.pinned === true,
    tint: str(raw?.tint),
    alerts: normalizeAlerts(raw?.alerts),
    links: normalizeIds(raw?.links),
    flag: normalizeFlag(raw),
    kind: raw?.kind === 'story' ? 'story' : '',
    tags: normalizeTagIds(raw?.tags),
    archived: raw?.archived === true,
    hasImage: raw?.hasImage === true,
    hasDrawing: raw?.hasDrawing === true
  }
}

/**
 * The notes a body links to, read straight out of the HTML.
 *
 * A regex rather than a parser: there is no DOM in the main process, and the
 * attribute is written by this app in exactly one place, so the shape is known.
 * The renderer does the same job with real DOM calls when it saves - this is only
 * for the one-off backfill of notebooks written before links existed.
 */
function linkTargets(html: string): string[] {
  const found = new Set<string>()
  for (const match of html.matchAll(/data-note="([^"]+)"/g)) {
    found.add(match[1])
  }
  return [...found]
}

/** A list of ids, from anything. Empty strings and duplicates are dropped. */
function normalizeIds(raw: unknown): string[] {
  if (!Array.isArray(raw)) {
    return []
  }
  const seen = new Set<string>()
  for (const value of raw) {
    const id = str(value)
    if (id.length > 0) {
      seen.add(id)
    }
  }
  return [...seen]
}

function normalizeCategory(raw: any): Category {
  const id = String(raw?.id ?? '')
  const subs: SubCategory[] = Array.isArray(raw?.subs)
    ? raw.subs.map(normalizeSub).filter((s: SubCategory) => s.id.length > 0)
    : []
  const subIds = new Set(subs.map((s) => s.id))
  return {
    id,
    name: str(raw?.name),
    color: str(raw?.color, '#9a9da3'),
    scope: normalizeScope(raw?.scope),
    open: raw?.open !== false,
    subs,
    notes: Array.isArray(raw?.notes)
      ? raw.notes
          .map((n: unknown) => normalizeNoteMeta(n, id, subIds))
          .filter((n: NoteMeta) => n.id.length > 0)
      : []
  }
}

function normalizeIndex(parsed: unknown): NibIndex {
  if (parsed === null || typeof parsed !== 'object') {
    return { ...EMPTY_INDEX }
  }
  const raw = parsed as { categories?: unknown; tags?: unknown; templates?: unknown }
  return {
    version: INDEX_VERSION,
    categories: Array.isArray(raw.categories)
      ? raw.categories.map(normalizeCategory).filter((c) => c.id.length > 0)
      : [],
    tags: normalizeTags(raw.tags),
    // A notebook written before templates existed has no list at all and gets
    // the defaults. An empty one is a choice and stays empty - somebody who
    // deleted every template should not find them back on the next launch.
    templates: normalizeTemplates(raw.templates)
  }
}

function normalizeTool(value: unknown): StrokeTool {
  return value === 'highlighter' || value === 'eraser' ? value : 'pen'
}

/**
 * A drawing file, read defensively.
 *
 * These files are the largest thing Nib writes and the most mechanical - a bad
 * number in a coordinate would reach a canvas call and throw there, far from the
 * cause. Every field is coerced here instead.
 */
function normalizeDrawing(id: string, parsed: unknown): DrawingDoc {
  const raw = (parsed ?? {}) as Partial<DrawingDoc>
  const strokes: Stroke[] = Array.isArray(raw.strokes)
    ? raw.strokes
        .filter((stroke) => stroke !== null && typeof stroke === 'object')
        .map((stroke) => ({
          tool: normalizeTool((stroke as Stroke).tool),
          color: str((stroke as Stroke).color, '#e8e9ec'),
          width: Math.min(64, Math.max(0.5, num((stroke as Stroke).width, 2))),
          points: Array.isArray((stroke as Stroke).points)
            ? (stroke as Stroke).points
                .filter((point) => point !== null && typeof point === 'object')
                .map((point) => ({
                  x: num(point.x, 0),
                  y: num(point.y, 0),
                  p: Math.min(1, Math.max(0, num(point.p, 0.5)))
                }))
            : []
        }))
        .filter((stroke) => stroke.points.length > 0)
    : []

  return {
    id,
    width: Math.max(1, num(raw.width, 800)),
    height: Math.max(1, num(raw.height, 480)),
    strokes,
    image: str(raw.image)
  }
}

/**
 * The storage layer: an index file for ordering and metadata, one file per note
 * for the bodies.
 *
 * One file per note is what makes embedded images survivable (see DECISIONS
 * 2026-08-19) and what keeps a synced folder happy: editing one note touches one
 * file, so two machines editing different notes never collide.
 *
 * The index is the exception - it is one shared file, and every reorder, rename
 * or metadata change rewrites it. It stays small because it holds no bodies, and
 * writes to it are serialised through a one-slot chain so two saves in flight can
 * never interleave.
 */
export class NoteStorage {
  private readonly dataDir: string
  private readonly indexPath: string
  private readonly notesDir: string
  private readonly drawingsDir: string
  private indexWrite: Promise<void> = Promise.resolve()

  constructor(dataDir: string) {
    this.dataDir = dataDir
    this.indexPath = join(dataDir, INDEX_FILE)
    this.notesDir = join(dataDir, NOTES_DIR)
    this.drawingsDir = join(dataDir, DRAWINGS_DIR)
  }

  get directory(): string {
    return this.dataDir
  }

  private notePath(id: string): string {
    return join(this.notesDir, `${safeId(id)}.json`)
  }

  private drawingPath(id: string): string {
    return join(this.drawingsDir, `${safeId(id)}.json`)
  }

  async loadIndex(): Promise<NibIndex> {
    try {
      const raw = await fs.readFile(this.indexPath, 'utf-8')
      return normalizeIndex(JSON.parse(raw.replace(/^﻿/, '')))
    } catch (error) {
      const code = (error as NodeJS.ErrnoException).code
      if (code === 'ENOENT') {
        return { ...EMPTY_INDEX }
      }
      throw error
    }
  }

  /**
   * Fill in `links` for a notebook written before they were recorded.
   *
   * Reads the version off the file rather than off the normalised index, which
   * always reports the current one. Returns true when it changed something, so
   * the caller knows to reload.
   *
   * Every note body is read once here. That is the most I/O this app does in one
   * go, and it happens once per notebook ever - the alternative was leaving every
   * existing note with no backlinks until it happened to be edited, which would
   * look exactly like the feature being broken.
   */
  async backfillLinks(): Promise<boolean> {
    let onDisk: unknown
    try {
      onDisk = JSON.parse((await fs.readFile(this.indexPath, 'utf-8')).replace(/^\ufeff/, ''))
    } catch {
      return false
    }
    const version = num((onDisk as { version?: unknown })?.version, 1)
    if (version >= INDEX_VERSION) {
      return false
    }

    const index = normalizeIndex(onDisk)
    for (const category of index.categories) {
      for (const meta of category.notes) {
        const doc = await this.readNote(meta.id)
        meta.links = doc === null ? [] : linkTargets(doc.html)
      }
    }
    await this.saveIndex(index)
    return true
  }

  /**
   * Serialised against itself: whatever the renderer sends last wins, and two
   * saves in flight can never interleave their writes.
   */
  async saveIndex(index: NibIndex): Promise<void> {
    const run = this.indexWrite.then(() =>
      writeFileAtomic(this.indexPath, JSON.stringify(normalizeIndex(index), null, 2))
    )
    // The stored chain swallows failures so one bad write does not poison every
    // later one; the promise returned to the caller still rejects.
    this.indexWrite = run.catch(() => undefined)
    await run
  }

  async readNote(id: string): Promise<NoteDoc | null> {
    try {
      const raw = await fs.readFile(this.notePath(id), 'utf-8')
      const parsed = JSON.parse(raw.replace(/^﻿/, '')) as Partial<NoteDoc>
      const created = num(parsed.created, Date.now())
      const subId = str(parsed.subId)
      return {
        id,
        categoryId: str(parsed.categoryId),
        subId: subId.length > 0 ? subId : null,
        title: str(parsed.title),
        html: str(parsed.html),
        created,
        edited: num(parsed.edited, created)
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return null
      }
      throw error
    }
  }

  async writeNote(doc: NoteDoc): Promise<void> {
    await writeFileAtomic(this.notePath(doc.id), JSON.stringify(doc, null, 2))
  }

  async readDrawing(id: string): Promise<DrawingDoc | null> {
    try {
      const raw = await fs.readFile(this.drawingPath(id), 'utf-8')
      return normalizeDrawing(id, JSON.parse(raw.replace(/^﻿/, '')))
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return null
      }
      throw error
    }
  }

  async writeDrawing(doc: DrawingDoc): Promise<void> {
    // Not pretty-printed: a drawing is thousands of coordinates, and indenting
    // them triples the file for nobody's benefit.
    await writeFileAtomic(this.drawingPath(doc.id), JSON.stringify(normalizeDrawing(doc.id, doc)))
  }

  async deleteDrawing(id: string): Promise<void> {
    await fs.unlink(this.drawingPath(id)).catch((error) => {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw error
      }
    })
  }

  /** Deleting a note with no file on disk is a success, not an error. */
  async deleteNote(id: string): Promise<void> {
    await fs.unlink(this.notePath(id)).catch((error) => {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw error
      }
    })
  }

  /**
   * Delete the images and drawings nothing refers to any more.
   *
   * Assets are content-addressed and shared: the same image pasted into two
   * notes is one file, so deleting a note - or a section of one - cannot simply
   * delete "its" images. What can be said is which files no note refers to at
   * all, and that is what this removes.
   *
   * The grace period is the safety catch. An image is written to disk the moment
   * it is pasted, and the note that refers to it is saved 600ms later; a sweep in
   * between would see an unreferenced file and delete the paste. Nothing younger
   * than the grace period is touched, so that window is never a race.
   *
   * Returns what it deleted, for the log.
   */
  async sweepOrphans(graceMs = 10 * 60 * 1000): Promise<{ assets: number; drawings: number }> {
    const noteFiles = await fs.readdir(this.notesDir).catch(() => [] as string[])
    const referencedAssets = new Set<string>()
    const referencedDrawings = new Set<string>()

    for (const file of noteFiles) {
      if (!file.endsWith('.json')) {
        continue
      }
      const raw = await fs.readFile(join(this.notesDir, file), 'utf-8').catch(() => '')
      for (const match of raw.matchAll(/nib-asset:\/\/asset\/([A-Za-z0-9_.-]+)/g)) {
        referencedAssets.add(match[1])
      }
      for (const match of raw.matchAll(/data-canvas=\?["']([A-Za-z0-9_-]+)/g)) {
        referencedDrawings.add(match[1])
      }
    }

    // A drawing that is still in a note keeps its rendered PNG alive even if the
    // block's img tag has been replaced since.
    for (const id of referencedDrawings) {
      const doc = await this.readDrawing(id).catch(() => null)
      const name = doc?.image.split('/').pop()
      if (name !== undefined && name.length > 0) {
        referencedAssets.add(name)
      }
    }

    const assets = await this.removeUnreferenced(
      join(this.dataDir, ASSETS_DIR),
      (file) => referencedAssets.has(file),
      graceMs
    )
    const drawings = await this.removeUnreferenced(
      this.drawingsDir,
      (file) => referencedDrawings.has(file.replace(/\.json$/, '')),
      graceMs
    )
    return { assets, drawings }
  }

  private async removeUnreferenced(
    directory: string,
    isReferenced: (file: string) => boolean,
    graceMs: number
  ): Promise<number> {
    const files = await fs.readdir(directory).catch(() => [] as string[])
    const cutoff = Date.now() - graceMs
    let removed = 0

    for (const file of files) {
      // Never touch a half-written temp file from an atomic write in flight.
      if (file.startsWith('.') || isReferenced(file)) {
        continue
      }
      const path = join(directory, file)
      const stat = await fs.stat(path).catch(() => null)
      if (stat === null || !stat.isFile() || stat.mtimeMs > cutoff) {
        continue
      }
      await fs.unlink(path).catch(() => undefined)
      removed++
    }
    return removed
  }

  /**
   * Watch the index for changes made outside this process - another machine's
   * Dropbox sync, or an external tool writing the file.
   *
   * Both mechanisms are needed. fs.watch is event-driven and fast but drops
   * events on Windows and in synced folders, exactly for the atomic tmp+rename
   * writes this module makes. fs.watchFile stat-polls and therefore never
   * misses. They funnel through one debounce so a burst produces one reload.
   */
  watchIndex(onChange: () => void): () => void {
    let closed = false
    let debounceTimer: NodeJS.Timeout | null = null

    const trigger = (): void => {
      if (closed) {
        return
      }
      if (debounceTimer !== null) {
        clearTimeout(debounceTimer)
      }
      debounceTimer = setTimeout(() => {
        debounceTimer = null
        onChange()
      }, 150)
    }

    void fs.mkdir(this.dataDir, { recursive: true }).catch((error) => {
      console.error('Failed to prepare the Nib data directory', error)
    })

    const targetFile = basename(this.indexPath)
    let watcher: ReturnType<typeof watchFs> | null = null
    try {
      watcher = watchFs(this.dataDir, (_event, filename) => {
        if (filename !== undefined && filename !== null && String(filename) !== targetFile) {
          return
        }
        trigger()
      })
    } catch (error) {
      // Non-fatal: the poll below still catches every change.
      console.error('Failed to start fs.watch on the Nib data directory', error)
      watcher = null
    }

    watchFileFs(this.indexPath, { interval: 1000 }, (curr, prev) => {
      if (curr.mtimeMs !== prev.mtimeMs || curr.size !== prev.size) {
        trigger()
      }
    })

    return () => {
      closed = true
      if (debounceTimer !== null) {
        clearTimeout(debounceTimer)
        debounceTimer = null
      }
      if (watcher !== null) {
        watcher.close()
      }
      unwatchFileFs(this.indexPath)
    }
  }
}
